### PR TITLE
ReImplemented Random Padding

### PR DESCRIPTION
**Pull request by ghost**
Here is a true and fast implementation of random padding

### CODE REVIEW

**Comment by pforemski** [comment]
Hi, sorry but I can't see neither "fast" nor "true" here :) As the query is encrypted, we don't need to worry about making the padding contents random. Did you try comparing the speed improvement of your version to the existing code? I can't see how it could be faster.

**Comment by ghost** [comment]
1. using the same character over and over generates very poor entropy, randomness of the padding is ideal. Also I can generate a string of random letters faster than the string function can generate the same letter multiple times :)

2. using rand.Intn() (multiple times) is slow, see https://stackoverflow.com/questions/22892120/how-to-generate-a-random-string-of-a-fixed-length-in-golang

**Comment by pforemski** [comment]
1. entropy of the clear-text information is exactly what a decent encryption scheme accounts for, thus we really don't need to make it random

2. we only call it twice per call in line 83, vs. a function call, memory allocation, and a quite heavy loop in what you submitted; btw, the link you provided makes it quite clear you just copied the code there, right? if so, sorry I'm not sure I can accept such a contribution (copyright issues?)

**Comment by ghost** [comment]
Hmm stackexchange is creative commons if you check. at any rate, you should really read more on cryptography and entropy before attempting to write cryptographically sensitive applications.

Good luck to you. I think as you educate yourself more you will see the the problems you have with your implementation. It appears from your bug lists I'm not the first to attempt to make contributions here for you. I suggest you remain open to suggestions and expertise of the larger community. 

Lucky for us forking exists :)

**Comment by pforemski** [comment]
Not a nice reply... Bye.

**Pull request closed without merging**
